
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pruebacup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_CI = 18;
  public static final int MENOS = 13;
  public static final int IGUAL = 28;
  public static final int INICIOCODIGO = 2;
  public static final int PARENTESIS_AP = 17;
  public static final int DIVIDIDO = 15;
  public static final int TIPO_PALABRA = 26;
  public static final int ERROR = 27;
  public static final int CUANDO = 7;
  public static final int TIPO_ENTERO = 24;
  public static final int IMPRIMIR = 8;
  public static final int MAYORQUE = 4;
  public static final int VARIABLE = 22;
  public static final int FINALIZADOR_LINEA = 21;
  public static final int FINCODIGO = 3;
  public static final int POR = 14;
  public static final int CORCHETE_CI = 20;
  public static final int ASIGNACION = 16;
  public static final int GUARDAR = 9;
  public static final int EOF = 0;
  public static final int MENORQUE = 5;
  public static final int CORCHETE_AP = 19;
  public static final int NUMERO = 23;
  public static final int error = 1;
  public static final int TIPO_DECIMAL = 25;
  public static final int MIENTRAS = 6;
  public static final int UNIR = 11;
  public static final int VAR = 10;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIOCODIGO",
  "FINCODIGO",
  "MAYORQUE",
  "MENORQUE",
  "MIENTRAS",
  "CUANDO",
  "IMPRIMIR",
  "GUARDAR",
  "VAR",
  "UNIR",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ASIGNACION",
  "PARENTESIS_AP",
  "PARENTESIS_CI",
  "CORCHETE_AP",
  "CORCHETE_CI",
  "FINALIZADOR_LINEA",
  "VARIABLE",
  "NUMERO",
  "TIPO_ENTERO",
  "TIPO_DECIMAL",
  "TIPO_PALABRA",
  "ERROR",
  "IGUAL"
  };
}

