Create Database SDA;
Use SDA

CREATE TABLE Usuario(
	IdUsuario INT IDENTITY NOT NULL PRIMARY KEY,
	NombreUsuario VARCHAR(100) NOT NULL,
	Clave VARCHAR(100) NOT NULL
);

CREATE TABLE Municipio(
	IdMunicipio INT IDENTITY NOT NULL PRIMARY KEY,
	NombreMunicipio VARCHAR(100) NOT NULL
);

CREATE TABLE Sexo (
	IdSexo INT IDENTITY NOT NULL PRIMARY KEY,
	NombreSexo VARCHAR(9) NOT NULL
);

CREATE TABLE Especies (
	IdEspecies INT IDENTITY NOT NULL PRIMARY KEY,
	NombreEspecie VARCHAR(50) NOT NULL
);

CREATE TABLE Propietario (
	IdPropietario INT IDENTITY NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	ApellidoPaterno VARCHAR(100) NOT NULL,
	ApellidoMaterno VARCHAR(100) NOT NULL,
	Edad INT NOT NULL,
	Curp VARCHAR(18) NOT NULL,
	Telefono VARCHAR(16) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	FechaRegistro DATE NOT NULL,
	IdSexo INT NOT NULL,
	IdMunicipio INT NOT NULL,
	IdUsuario INT NOT NULL,
	CONSTRAINT FK_IDSEXO FOREIGN KEY (IdSexo) REFERENCES Sexo(IdSexo),
	CONSTRAINT FK_IDMUNICIPIO FOREIGN KEY (IdMunicipio) REFERENCES Municipio(IdMunicipio),
	CONSTRAINT FK_IDUSUARIO FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Rancho(
	IdRancho INT IDENTITY NOT NULL PRIMARY KEY,
	NombreRancho VARCHAR(100) NOT NULL,
	GpsLatitud VARCHAR(50) NOT NULL,
	GpsLongitud VARCHAR(50) NOT NULL,
	IdMunicipio	INT NOT NULL,
	IdPropietario INT NOT NULL,
	CONSTRAINT FK_IDMUNICIPIORANCHO FOREIGN KEY (IdMunicipio) REFERENCES Municipio(IdMunicipio),
	CONSTRAINT FK_IDPROPIETARIORANCHO FOREIGN KEY (IdPropietario) REFERENCES Propietario(IdPropietario)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Empleado(
	IdEmpleado INT IDENTITY NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	ApellidoPaterno VARCHAR(100) NOT NULL,
	ApellidoMaterno VARCHAR(100) NOT NULL,
	Edad INT NOT NULL,
	Curp  VARCHAR(18) NOT NULL,
	Oficio VARCHAR(50) NOT NULL,
	Telefono VARCHAR(16) NOT NULL,
	FechaRegistro DATE NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	IdSexo INT NOT NULL,
	IdPropietario INT NOT NULL,
	IdUsuario INT NOT NULL,
	CONSTRAINT FK_EMPLEADO_IDSEXO FOREIGN KEY (IdSexo)  REFERENCES Sexo(IdSexo),
	CONSTRAINT FK_EMPLEADO_IDPROPIETARIO FOREIGN KEY (IdPropietario) REFERENCES Propietario(IdPropietario),
	CONSTRAINT FK_EMPLEADO_IDUSUARIO FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Animal(
	IdAnimal INT IDENTITY NOT NULL PRIMARY KEY,
	Folio VARCHAR(15) NOT NULL,
	Raza VARCHAR(50) NOT NULL,
	NumeroArete VARCHAR(6) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Procedencia VARCHAR(100) NOT NULL,
	Peso FLOAT NOT NULL,
	Color TEXT NOT NULL,
	Caracter VARCHAR(70) NOT NULL,
	Foto VARCHAR(200) NOT NULL,
	FechaRegistro DATE NOT NULL,
	IdEspecie INT NOT NULL,
	IdPropietario INT NOT NULL,
	IdSexo INT NOT NULL,
	IdRancho INT NOT NULL,
	IdEmpleado INT NOT NULL
	CONSTRAINT FK_ANIMAL_IDESPECIE FOREIGN KEY (IdEspecie) REFERENCES Especies(IdEspecies),
	CONSTRAINT FK_ANIMAL_IDSEXO FOREIGN KEY (Idsexo) REFERENCES Sexo(IdSexo),
	CONSTRAINT FK_ANIMAL_IDPROPIETARIO FOREIGN KEY (IdPropietario) REFERENCES Propietario(IdPropietario),
	CONSTRAINT FK_ANIMAL_IDRANCHO FOREIGN KEY (IdRancho) REFERENCES Rancho(IdRancho),
	CONSTRAINT FK_ANIMAL_IDEMPLADO FOREIGN KEY (IdEmpleado) REFERENCES Empleado(IdEmpleado)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Vacuna(
	IdVacuna INT IDENTITY NOT NULL PRIMARY KEY,
	NombreVacuna VARCHAR(100) NOT NULL,
	FechaAplicacion DATE NOT NULL,
	Comentario TEXT NOT NULL,
	IdAnimal INT NOT NULL,
	CONSTRAINT FK_VACUNA_IDANIMAL FOREIGN KEY (IdAnimal) REFERENCES Animal(IdAnimal)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Enfermedad(
	IdEnfermedad INT IDENTITY NOT NULL PRIMARY KEY,
	NombreEnfermedad VARCHAR(100) NOT NULL,
	FechaContagio DATE NOT NULL,
	Comentario TEXT NOT NULL,
	IdAnimal INT NOT NULL,
	CONSTRAINT FK_ENFERMEDAD_IDANIMAL FOREIGN KEY (IdAnimal) REFERENCES Animal(IdAnimal)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE Venta(
	IdVenta INT IDENTITY NOT NULL PRIMARY KEY,
	Peso FLOAT NOT NULL,
	Precio FLOAT NOT NULL,
	FechaVenta DATE NOT NULL,
	IdAnimal INT NOT NULL,
	CONSTRAINT FK_VENTA_IDANIMAL FOREIGN KEY (IdAnimal) REFERENCES Animal(IdAnimal)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);